
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-app
  labels:
        app: invoice-app
spec:
  type: NodePort
  selector:
    app: invoice-app
  externalTrafficPolicy: Local
  sessionAffinity: "ClientIP"
  sessionAffinityConfig:
    clientIP: 
      timeoutSeconds: 10
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: invoice-app
data:
  payment_url: "http://payment-provider:8082/payments/pay"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: invoice-app
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: invoice-app
    spec:
      containers:
      - name: invoice-app
        image: danielademeso/invoice-app:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: app-port
          timeoutSeconds: 5
        ports:
          - name: app-port
            containerPort: 8081
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        envFrom:
        - configMapRef:
            name: invoice-app
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000

